# Interactive Fisheries Stock Assessment Hub

This interactive Shiny application helps users explore data inputs and stock assessment results for fisheries management. It was developed to enhance understanding of the relationships between data, model assumptions, and fisheries outcomes. This tool is still under development and feedback is welcome!

🌐 **Live App:** [I-FSH](https://itz9y3-jerelle-jesse.shinyapps.io/mrep-shiny/)

------------------------------------------------------------------------

## Features

-   **Interactive Visualizations**: Explore stock assessment results with intuitive plots and tables.
-   **Data Adjustment Scenarios**: Experiment with input data and see real-time impacts.
-   **Educational Insights**: Understand the implications of data and assumptions on stock assessment models and fisheries management.

## Usage

-   **Home:** Introduction to the tool and American Plaice, our example stock.

-   **Stock Assessment Inputs:** Select common stock assessment data inputs or assumptions to learn more.

-   **Stock Assessment Results:** Explore some of the most common stock assessment results.

-   **Changes in Catch:** Adjust catch higher or lower and explore the changes in the stock assessment results.

-   **Changes in Indices:** Adjust indices of abundance lower and explore the changes in the stock assessment results.

## Feedback

-   We aim to make a realistic, relevant, and interactive experience for participants of the Marine Resource Education Program (MREP).

-   This web application is still under development. Please provide feedback using the form at the bottom of the menu!

## Contact

For questions, feedback, or collaboration inquiries, please reach out:

**[Jerelle Jesse]**\
📧 [jerelle.jesse\@maine.edu](mailto:your.email@example.com)
